Add links for regulation
cesium/themis pull request #17
Opened 2023-03-09 16:13 UTC by GresosJ

2023-03-09 16:36 UTC, tiago-bacelar requested changes

2023-03-09 16:36 UTC, tiago-bacelar commented on src/components/Paper.jsx
> +                <Link className="font-mono text-xs tracking-tighter text-slate-600" href="/">Regulamentação</Link>
I think these should be bigger and have some visual indication that they are links (like being underlined and/or a different color)

2023-03-09 16:36 UTC, tiago-bacelar commented on src/components/Paper.jsx
> +                <Button type="submit" className="ml-20 mt-2 sm:ml-24" href="/">
Just my opinion, but I don't like the position of the button in mobile... I think it would be better after the text instead of below it

2023-03-09 20:52 UTC, MarioRodrigues10 submitted a review, later dismissed
Please run formatter.

2023-03-12 16:30 UTC, tiago-bacelar approved these changes, later dismissed
Looks good. Don't forget to run the formatter before merging :)

2023-03-12 18:21 UTC, RuiL1904 commented on src/components/Paper.jsx
> +                  Mais informações
```suggestion
                  Mais informações{' '}
```

In order to have a space between the text and the arrow 🙏🏼

2023-03-12 18:55 UTC, RuiL1904 approved these changes
Great work! 🙌🏼
Just something that I've noticed: next time use hyphen separated words to the branch's name. That's our convention 🙏🏼

2023-03-12 22:33 UTC, merged