Add: texts
cesium/themis pull request #21
Opened 2023-03-14 18:08 UTC by AdrianaBot

@franl08 quero review da minha excelente prosa, or else. 🥺🔪
@GresosJ review. :D

(não corrijam nada, quero um PR só meu 🤓)

2023-03-14 18:24 UTC, franl08 commented
@AdrianaBot "alguns dos indivíduos" -> algumas das pessoas
de resto top :ok_hand:

2023-03-14 18:48 UTC, GresosJ reviewed
You need to run the code -> npm run format , for the code be formatted

2023-03-15 13:58 UTC, tiago-bacelar requested changes

2023-03-15 13:58 UTC, tiago-bacelar commented on src/components/Blog.jsx
> +              Foram três dias de novo conhecimento, tecnologias <i>cutting-edge</i>
There's a space missing here :)

![image](https://user-images.githubusercontent.com/70779845/225330510-8fa4bf9a-79cf-4733-9b71-74bca8d2758e.png)

Try moving the <i>cutting-edge</i> to the middle of a line

2023-03-15 15:59 UTC, GresosJ approved these changes, later dismissed

2023-03-15 16:30 UTC, tiago-bacelar requested changes
Now there's a space missing before the cutting-edge :sweat_smile:

![image](https://user-images.githubusercontent.com/70779845/225376360-37daa05a-ee75-41c3-818e-98a5a6f42574.png)

If the formatter is messing with you you can try to put an explicit space character (like this: {' '}) in the text.

2023-03-16 15:51 UTC, GresosJ submitted a review, later dismissed

2023-03-16 15:52 UTC, GresosJ reviewed
Pls run -> npm run format

2023-03-16 19:53 UTC, ruilopesm commented on src/components/Blog.jsx
> +              {''}<i>cutting-edge</i> e uma das áreas emergentes mais fascinantes da
```suggestion
              {' '}<i>cutting-edge</i> e uma das áreas emergentes mais fascinantes da
```

2023-03-19 19:28 UTC, RuiL1904 commented
@AdrianaBot Can you run `npm run format` and follow my suggestion? 🙏🏼

2023-03-20 15:23 UTC, GresosJ approved these changes

2023-03-20 16:28 UTC, tiago-bacelar approved these changes
All good! :)

2023-03-20 16:35 UTC, merged