Fix some details
cesium/themis pull request #28
Opened 2023-04-15 15:56 UTC by MarioRodrigues10

2023-04-15 19:38 UTC, MarioRodrigues10 commented on src/components/Organization.jsx
> +                    <p className="hidden">{organization.logo}</p>
Please don't ask me to change this line, because somehow without it it isn't working

2023-04-15 19:38 UTC, MarioRodrigues10 commented on src/components/Organization.jsx
> +                    <p className="hidden">{organization.logo_light}</p>
Please don't ask me to change this line, because somehow without it it isn't working

2023-04-16 14:41 UTC, tiago-bacelar reviewed
I'm pretty sure the library stores your current theme in localStorage automatically...
![image](https://user-images.githubusercontent.com/70779845/232320288-2a394323-dff3-45f9-84e3-2b7fcdf1cca5.png)
This print is from the current main branch.
Also, I just read the docs and apparently there is a resolvedTheme attribute inside useTheme that already substitutes 'system' for 'light' or 'dark', so my bad :sweat_smile:
Reading docs is wild, yall!

2023-04-16 14:54 UTC, tiago-bacelar requested changes

2023-04-16 14:54 UTC, tiago-bacelar commented on src/components/Header.jsx
> +  const { systemTheme, theme = 'light', setTheme } = useTheme()
One more thing. I've noticed a bug where when you first load the page, the logos/images will be the wrong theme. That goes away by removing this.
```suggestion
  const { systemTheme, theme, setTheme } = useTheme()
```

If you want to set a default theme, consider using the <ThemeProvider> in _app.js

2023-04-16 14:54 UTC, tiago-bacelar commented on src/components/Organization.jsx
> +  const { systemTheme, theme = 'light', setTheme } = useTheme()
```suggestion
  const { systemTheme, theme, setTheme } = useTheme()
```

2023-04-16 14:54 UTC, tiago-bacelar commented on src/components/Sponsors.jsx
> +  const { systemTheme, theme = 'light', setTheme } = useTheme()
```suggestion
  const { systemTheme, theme, setTheme } = useTheme()
```

2023-04-16 15:53 UTC, MarioRodrigues10 commented
> I'm pretty sure the library stores your current theme in localStorage automatically... ![image](https://user-images.githubusercontent.com/70779845/232320288-2a394323-dff3-45f9-84e3-2b7fcdf1cca5.png) This print is from the current main branch. Also, I just read the docs and apparently there is a resolvedTheme attribute inside useTheme that already 
substitutes 'system' for 'light' or 'dark', so my bad sweat_smile Reading docs is wild, yall!


Yap it does but it isn't working very properly, and that's what i solve with this PR.
![image](https://user-images.githubusercontent.com/93675410/232324761-52189e1a-6a04-4d27-94ff-ec80a3998971.png)

2023-04-16 22:15 UTC, tiago-bacelar requested changes
I'm getting an error when refreshing in dark mode:
![image](https://user-images.githubusercontent.com/70779845/232345620-0a90038a-8610-41c9-b4e0-12605f1e29ca.png)
Possible fix: https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

2023-04-16 22:17 UTC, MarioRodrigues10 commented
> I'm getting an error when refreshing in dark mode: ![image](https://user-images.githubusercontent.com/70779845/232345620-0a90038a-8610-41c9-b4e0-12605f1e29ca.png) Possible fix: [pacocoursey/next-themes#avoid-hydration-mismatch](https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch)

that only happens in development environment for some reason

2023-04-16 23:16 UTC, tiago-bacelar approved these changes
@RuiL1904 was clearly this PR's MVP

2023-04-16 23:17 UTC, merged